name = input('이름 : ')
subject = input('학과 : ')
address = input('주소 : ')
hobby = input('취미 : ')
print('****** 자기소개서 ******')
print('이름 : ', name)
print('학과 : ', subject)
print('주소 : ', address)
print('취미 : ', hobby)
print('*' * 27)
